name: SpigotTips
version: 0.0.1
main: dev.ekuinox.spigot_tips.Plugin
api-version: "1.15"
commands:
  tips:
    description: custom tips
    usage: /tips help
permissions:
  tips.*:
    default: op
    children:
      tips.create: true
      tips.show: true
      tips.help: true
  tips.create:
    default: op
  tips.show:
    default: true
  tips.help:
    default: true
